[package]
name = "loadngo-gfx-metal"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
loadngo-host-core = { path = "../host-core" }
loadngo-renderer = { path = "../renderer" }
ui-core = { path = "../ui-core" }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc2 = "0.6.4"