[package]
name = "network"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
data = { path = "../data" }
loadngo-proactor = { path = "../proactor" }
socket2 = "0.5"

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
tempfile = "3"
